name: Build docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build and push the Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: kelzceana/prime-video-app
        tags: v1, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


  deploy:
    needs: build
    runs-on : ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
    
    steps:
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      
      - name: terraform init
        working-directory: ./terraform/
        run: |
          terraform init
          terraform plan

      - name: terraform apply
        working-directory: ./terraform/
        run: terraform apply -auto-approve

      - name: terraform output
        working-directory: infra/
        run: |
            echo "EC2_HOST=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV

      - name: Deploy to EC2
        run: |
          echo "$PRIVATE_KEY" > ec2-key.pem
          chmod 600 ec2-key.pem
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_HOST << 'EOF'
            docker pull kelzceana/prime-video-app:latest
            docker rm -f prime-video-app-container || true
            docker run -d -p 3000:3000 --name prime-video-app-container kelzceana/prime-video-app:latest
          EOF
        




